#! /bin/bash

cfg_file=./.pvrdma_start_vm.cfg 

# Default settings
qemu=$HOME/qemu/x86_64-softmmu/qemu-system-x86_64
images_dir=$HOME/disks/
base_image=pvrdma-fc27-0.qcow2
vnc_ip=localhost
mem=1G
cpus=1
snapshot="-snapshot"
hdb=""
log_dir=/tmp

if [ -f ${cfg_file} ];
then
	. ${cfg_file}
fi


if [ $# -ne 3 ]
then
	echo "Usage: $0 mng_if roce_if ipv6_idx"
	exit 1
fi

if [ ! -f ${qemu} ];
then
	echo "Can't find qemu exec"
	exit 2
fi

if [ ! -f ${images_dir}/${base_image} ];
then
	echo "Can't find base image"
	exit 3
fi

mng_eth=$1
eth=$2
idx=$3

vm_name="${mng_eth}-${eth}-${idx}"
log=${log_dir}/pvrdma-${vm_name}.log
vm_img_file=pvrdma-${vm_name}.qcow2

ifconfig ${mng_eth} > /dev/null 2>&1
if [ $? -ne 0 ];
then
	echo "Can't find interface ${mng_eth}"
	exit 4
fi
ifconfig ${eth} > /dev/null 2>&1
if [ $? -ne 0 ];
then
	echo "Can't find interface ${eth}"
	exit 5
fi

backend_dev=$(ls /sys/class/net/${eth}/device/infiniband 2>/dev/null)
# Lets see first that RXE is configured
if [ $? != 0 ];
then
	echo "Please run configure_pvrdma first"
	exit 6
fi

# If this is RXE setup then start from gid 3
#is_roce=$(ls /sys/class/net/${eth}/device/|grep infiniband|wc -l)
if [ $(ethtool -i ${eth}|grep driver|grep mlx|wc -l) -eq 0 ];
then
	macvtap_idx=$((${idx} + 2))
else
	macvtap_idx=${idx} 
fi
macvtap_idx=${idx} 

ipv6=$(ifconfig ${eth}|grep inet6|grep fe80|head -n ${idx}|tail -1|awk '{print $2}')
if [ "x${ipv6}" == "x" ];
then
	echo "No IPv6 at index ${idx}"
	exit 7
fi

s=$(echo ${ipv6}|awk -F:: '{print $2}')
s=$(echo ${s}|awk -F: '{print $1}')
fn=$(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*)
# We take the odd entry since it supports RoCE v2
backend_gid_idx=$(basename $(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*|tail -1))

backend_port=1
pci_addr_roce=10
pci_addr_local=11

uniq_id=$((0x$(sha1sum <<<${mng_eth}${eth}${idx}|cut -c1-2)))
vnc=${vnc_ip}:${uniq_id}
tcp_port=$((10000 + ${uniq_id}))

pvrdma_args="-device pvrdma,addr=${pci_addr_roce}.1,backend-dev=${backend_dev},backend-gid-idx=${backend_gid_idx},backend-port=${backend_port}"

# For managment interface get macvtap MAC
tapifindex=$(cat /sys/class/net/${eth}_${macvtap_idx}/ifindex)
macvtap_mac=$(cat /sys/class/macvtap/tap${tapifindex}/device/address)

# For pvrdma Ethernet function (vmxnet3) make MAC from GID
f1=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($5,1,2)}')
f1=$((0x$f1 ^ 2))
f1=$(printf "%x\n" ${f1})
f2=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($5,3,2)}')
f3=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($6,1,2)}')
f4=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($7,3,2)}')
f5=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($8,1,2)}')
f6=$(cat /sys/class/infiniband/${backend_dev}/ports/${backend_port}/gids/${backend_gid_idx}|awk -F: '{print substr($8,3,2)}')
pvrdma_mac="${f1}:${f2}:${f3}:${f4}:${f5}:${f6}"

eth_for_pvrdma="-netdev user,id=id0,hostfwd=tcp::${tcp_port}-:22 -device vmxnet3,addr=${pci_addr_roce},multifunction=on,mac=${pvrdma_mac},netdev=id0"

eth_for_macvtap="-netdev tap,id=tap0,fd=3 3<>/dev/tap${tapifindex} -device e1000,addr=${pci_addr_local},mac=${macvtap_mac},netdev=tap0"

if [ ! -f ${images_dir}/${vm_img_file} ];
then
	cd ${images_dir}
	qemu-img create -f qcow2 -o backing_file=${base_image} ${vm_img_file}
	cd -
fi

cmd="$qemu -name ${vm_name} ${snapshot} -display vnc=${vnc} -object memory-backend-ram,id=mb1,size=${mem},share -numa node,memdev=mb1 -m ${mem} -smp ${cpus} --enable-kvm -hda ${images_dir}/${vm_img_file} ${hdb} ${pvrdma_args} ${eth_for_pvrdma} ${eth_for_macvtap} >${log} &"

rm -f /tmp/exec.$$
echo ${cmd} > /tmp/exec.$$
chmod +x /tmp/exec.$$
/tmp/exec.$$ &
sleep 2
rm -f /tmp/exec.$$
