#!/bin/bash

dev=$1
gid_idx=$2
cycles=$3
srv_addr=$4
sizes="8196 1048576 2097152 3145728 8388608 16777216 67108864 134217728"

for s in ${sizes}; do
        r=$(ibv_rc_pingpong -d ${dev} -g ${gid_idx} -n ${cycles} -s ${s} ${srv_addr}| grep "Mbit/sec"|awk '{print $7}')
        echo "${s}: ${r}"
	if [ "x${srv_addr}" != "x" ];
	then
		sleep 5
	fi
done
