#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: $0 netdev"
	exit 1
fi

eth=$1

brctl addbr bridge1
ifconfig bridge1 up

ifconfig ${eth} > /dev/null 2>&1
if [ $? -ne 0 ];
then
	echo "Can't find netdev ${eth}"
	exit 2
fi

# IB Modules
modprobe -r ib_uverbs;modprobe -r ib_umad;modprobe -r rdma_rxe;modprobe -r ib_core
modprobe ib_core; modprobe ib_umad; modprobe rdma_ucm; modprobe ib_uverbs;

# If not Mellanox RoCE device then let's start rxe
if [ $(ethtool -i ${eth}|grep driver|grep mlx|wc -l) -eq 0 ]
then
	modprobe rdma_rxe;
	echo ${eth} > /sys/module/rdma_rxe/parameters/add
fi
