#!/bin/bash

cycles=$1
srv_addr=$2
dev=vmw_pvrdma0
sizes="8196 1048576 2097152 3145728 8388608 16777216 67108864 134217728"

for s in ${sizes}; do
        r=$(ibv_rc_pingpong -d ${dev} -g 0 -n ${cycles} -s ${s} ${srv_addr}| grep "Mbit/sec"|awk '{print $7}')
        echo "${s}: ${r}"
	if [ "x${srv_addr}" != "x" ];
	then
		sleep 5
	fi
done
