#!/bin/bash

if [ $# -ne 1 ];
then
	echo "Usage: $0 roce_if ipv6_idx"
	exit 1
fi

name_idx=$1

if [ $(ps -ef|grep qemu|grep pvrdma|awk -Fname '{print $2}'|awk '{print $1}'|grep $name_idx|wc -l) -ne 1 ];
then
	echo "VM $1 is down"
	exit 2
fi

eth=$(echo ${name_idx}|awk -F\- '{print $1}')
idx=$(echo ${name_idx}|awk -F\- '{print $2}')

vnc_id=$((0x$(sha1sum <<<${eth}${idx}|cut -c1-2)))
vncviewer localhost:${vnc_id}
